name: Deploy Astro to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install, build & prepare for Pages
        uses: withastro/action@v3
        with:
          # si usas pnpm o yarn, especifica package-manager: 'pnpm' / 'yarn'
          # package-manager: 'npm'   # opcional (auto-detect)
          args: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # no inputs needed — deploys the prepared output
          # (actions/deploy-pages leerá la salida preparada por withastro/action)
